// GENERATED by Tools/bake-lut/gen_spaces.py -- do not edit.
// Derived from OCIO built-in config studio-config-v4.0.0_aces-v2.0_ocio-v2.5
// Chromaticities are computed by pushing each space's RGB basis through
// ACES2065-1 into CIE XYZ, not transcribed from published tables.

#include "EXRCore/exr_spaces.h"

namespace exrcore {

const NamedSpace kSpaces[] = {
    {"acescg", "ACEScg (AP1)", "lin_ap1_scene",
     "ACEScg|ACES - ACEScg|lin_ap1|lin_ap1_scene",
     {0.713000f, 0.293000f, 0.165000f, 0.830000f, 0.128000f, 0.044000f, 0.321680f, 0.337670f}},
    {"aces2065_1", "ACES2065-1 (AP0)", "lin_ap0_scene",
     "ACES2065-1|aces2065_1|aces|ACES - ACES2065-1|lin_ap0|lin_ap0_scene",
     {0.734700f, 0.265300f, 0.000000f, 1.000000f, 0.000100f, -0.077000f, 0.321680f, 0.337670f}},
    {"linear_rec_709_srgb", "Linear Rec.709 / sRGB", "lin_rec709_scene",
     "Linear Rec.709 (sRGB)|lin_rec709_srgb|lin_rec709|lin_rec709_scene|lin_srgb|Utility - Linear - sRGB|Utility - Linear - Rec.709",
     {0.642493f, 0.330357f, 0.305713f, 0.599990f, 0.151431f, 0.061512f, 0.321680f, 0.337670f}},
    {"linear_p3_d65", "P3-D65", "lin_p3d65_scene",
     "Linear P3-D65|lin_p3d65|lin_displayp3|lin_p3d65_scene|Utility - Linear - P3-D65|Linear Display P3",
     {0.680587f, 0.319839f, 0.270204f, 0.686004f, 0.151431f, 0.061512f, 0.321680f, 0.337670f}},
    {"linear_rec_2020", "Rec.2020", "lin_rec2020_scene",
     "Linear Rec.2020|lin_rec2020|lin_rec2020_scene|Utility - Linear - Rec.2020",
     {0.708189f, 0.292445f, 0.175356f, 0.791120f, 0.130569f, 0.046293f, 0.321680f, 0.337670f}},
    {"linear_adobergb", "Adobe RGB (1998)", "lin_adobergb_scene",
     "Linear AdobeRGB|lin_adobergb|lin_adobergb_scene|Utility - Linear - Adobe RGB",
     {0.642493f, 0.330357f, 0.215341f, 0.708158f, 0.151431f, 0.061512f, 0.321680f, 0.337670f}},
    {"linear_arri_wide_gamut_3", "ARRI Wide Gamut 3", "ocio:lin_awg3_scene",
     "Linear ARRI Wide Gamut 3|lin_arri_wide_gamut_3|lin_alexawide|Input - ARRI - Linear - ALEXA Wide Gamut|ocio:lin_awg3_scene",
     {0.684901f, 0.312906f, 0.227558f, 0.836295f, 0.077689f, -0.119414f, 0.321680f, 0.337670f}},
    {"linear_arri_wide_gamut_4", "ARRI Wide Gamut 4", "ocio:lin_awg4_scene",
     "Linear ARRI Wide Gamut 4|lin_arri_wide_gamut_4|lin_awg4|ocio:lin_awg4_scene",
     {0.734602f, 0.265916f, 0.149533f, 0.851404f, 0.093424f, -0.039552f, 0.321680f, 0.337670f}},
    {"linear_bmd_widegamut_gen5", "Blackmagic Wide Gamut Gen5", "ocio:lin_bmdwg5_scene",
     "Linear BMD WideGamut Gen5|lin_bmd_widegamut_gen5|ocio:lin_bmdwg5_scene",
     {0.716210f, 0.316092f, 0.234491f, 0.848010f, 0.094300f, -0.096555f, 0.321680f, 0.337670f}},
    {"linear_cinemagamut_d55", "Canon Cinema Gamut", "ocio:lin_cgamutd55_scene",
     "Linear CinemaGamut D55|lin_cinemagamut_d55|lin_canoncgamutday|Input - Canon - Linear - Canon Cinema Gamut Daylight|ocio:lin_cgamutd55_scene",
     {0.739295f, 0.270358f, 0.178600f, 1.098631f, 0.070849f, -0.117329f, 0.321680f, 0.337670f}},
    {"linear_davinci_widegamut", "DaVinci Wide Gamut", "ocio:lin_dwg_scene",
     "Linear DaVinci WideGamut|lin_davinci_widegamut|ocio:lin_dwg_scene",
     {0.792309f, 0.310314f, 0.176026f, 0.966000f, 0.069436f, -0.134870f, 0.321680f, 0.337670f}},
    {"linear_d_gamut", "DJI D-Gamut", "ocio:lin_dgamut_scene",
     "Linear D-Gamut|lin_dgamut|ocio:lin_dgamut_scene",
     {0.709359f, 0.309441f, 0.216756f, 0.866104f, 0.082452f, -0.094575f, 0.321680f, 0.337670f}},
    {"linear_redwidegamutrgb", "RED Wide Gamut RGB", "ocio:lin_rwg_scene",
     "Linear REDWideGamutRGB|lin_redwidegamutrgb|lin_rwg|Input - RED - Linear - REDWideGamutRGB|ocio:lin_rwg_scene",
     {0.774427f, 0.302633f, 0.131725f, 1.391817f, 0.089945f, -0.097819f, 0.321680f, 0.337670f}},
    {"linear_s_gamut3", "Sony S-Gamut3", "ocio:lin_sgamut3_scene",
     "Linear S-Gamut3|lin_sgamut3|Input - Sony - Linear - S-Gamut3|ocio:lin_sgamut3_scene",
     {0.729479f, 0.280182f, 0.147107f, 0.849231f, 0.094129f, -0.060845f, 0.321680f, 0.337670f}},
    {"linear_s_gamut3_cine", "Sony S-Gamut3.Cine", "ocio:lin_sgamut3cine_scene",
     "Linear S-Gamut3.Cine|lin_sgamut3cine|Input - Sony - Linear - S-Gamut3.Cine|ocio:lin_sgamut3cine_scene",
     {0.763140f, 0.274700f, 0.231497f, 0.792298f, 0.081211f, -0.102456f, 0.321680f, 0.337670f}},
    {"linear_venice_s_gamut3", "Sony Venice S-Gamut3", "ocio:lin_sgamut3venice_scene",
     "Linear Venice S-Gamut3|lin_venice_sgamut3|Input - Sony - Linear - Venice S-Gamut3|ocio:lin_sgamut3venice_scene",
     {0.739245f, 0.279372f, 0.096486f, 0.888866f, 0.105782f, -0.063494f, 0.321680f, 0.337670f}},
    {"linear_venice_s_gamut3_cine", "Sony Venice S-Gamut3.Cine", "ocio:lin_sgamut3cinevenice_scene",
     "Linear Venice S-Gamut3.Cine|lin_venice_sgamut3cine|Input - Sony - Linear - Venice S-Gamut3.Cine|ocio:lin_sgamut3cinevenice_scene",
     {0.772310f, 0.274042f, 0.195538f, 0.821304f, 0.095019f, -0.104590f, 0.321680f, 0.337670f}},
    {"linear_v_gamut", "Panasonic V-Gamut", "ocio:lin_vgamut_scene",
     "Linear V-Gamut|lin_vgamut|Input - Panasonic - Linear - V-Gamut|ocio:lin_vgamut_scene",
     {0.729324f, 0.280521f, 0.170487f, 0.830656f, 0.095537f, -0.037093f, 0.321680f, 0.337670f}},
};

const int kSpaceCount = 18;

}  // namespace exrcore
