#!/usr/bin/env python3
"""
Extracts the facts the layer rules use from Vendor/corpus/ into committed,
diff-friendly files under Tests/Fixtures/realworld/:

  channels.tsv   one line per file / part / channel -- input to test_realworld
  colour.tsv     per part: chromaticities, colorInteropID, writer hints
  SOURCES.md     every source with its licence and how many files it gave

Only names and attributes are written -- never pixels -- so the committed
manifest redistributes no imagery.

    manifest.py
"""
import collections
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import exrheader  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
CORPUS = os.path.join(ROOT, "Vendor", "corpus")
OUT = os.path.join(ROOT, "Tests", "Fixtures", "realworld")


def clean(s):
    return "" if s is None else str(s).replace("\t", " ").replace("\n", " ")


def main():
    index = json.load(open(os.path.join(CORPUS, "index.json")))
    os.makedirs(OUT, exist_ok=True)
    per_source = collections.Counter()
    licences = {}
    credits = {}
    skipped = []
    chan_lines = ["# file<TAB>id<TAB>source / part<TAB>name<TAB>type / channel<TAB>name",
                  "# Generated by Tools/corpus/manifest.py from Vendor/corpus/ -- do not edit."]
    colour_lines = ["file\tpart\tchromaticities\tcolorInteropID\thints"]
    for fid in sorted(index):
        meta = index[fid]
        path = os.path.join(CORPUS, fid)
        if not os.path.exists(path):
            continue
        try:
            h = exrheader.summarise(exrheader.parse(open(path, "rb").read()))
        except (exrheader.NeedMore, ValueError) as e:
            skipped.append((fid, str(e) or "truncated"))
            continue
        per_source[meta["source"]] += 1
        licences[meta["source"]] = meta["licence"]
        credits[meta["source"]] = meta["credit"]
        chan_lines.append(f"F\t{fid}\t{meta['source']}")
        for p in h["parts"]:
            chan_lines.append(f"P\t{clean(p['name'])}\t{clean(p['type'])}\t{clean(p['colorInteropID'])}")
            for c in p["channels"]:
                chan_lines.append(f"C\t{clean(c)}")
            colour_lines.append("\t".join([fid, clean(p["name"]),
                                           clean(p["chromaticities"]),
                                           clean(p["colorInteropID"]),
                                           clean(json.dumps(p.get("hints", {}), sort_keys=True))]))
    open(os.path.join(OUT, "channels.tsv"), "w").write("\n".join(chan_lines) + "\n")
    open(os.path.join(OUT, "colour.tsv"), "w").write("\n".join(colour_lines) + "\n")

    md = ["# Real-world header corpus", "",
          "Part and channel names from openly licensed production and test files,",
          "used by `EXRCore/tests/test_realworld.cpp` to check the layer rules against",
          "how real applications actually name things. Only names and attributes are",
          "committed here, never pixels. Rebuild with `Tools/corpus/build_corpus.py`",
          "then `Tools/corpus/manifest.py`.", "",
          "| Source | Files | Licence | Credit |", "|---|---|---|---|"]
    for sid in sorted(per_source):
        md.append(f"| {sid} | {per_source[sid]} | {licences[sid]} | {credits[sid]} |")
    md += ["", f"Total: {sum(per_source.values())} files."]
    if skipped:
        md += ["", "Skipped (unreadable header):", ""] + [f"- `{f}`: {why}" for f, why in skipped]
    open(os.path.join(OUT, "SOURCES.md"), "w").write("\n".join(md) + "\n")
    print(f"{sum(per_source.values())} files from {len(per_source)} sources; {len(skipped)} skipped")
    for sid in sorted(per_source):
        print(f"  {sid:<14} {per_source[sid]}")


if __name__ == "__main__":
    main()
