#!/usr/bin/env python3
"""
Generates the assumed-input colourspace table from the OCIO ACES 2.0 Studio
config.

The chromaticities are *derived*, never transcribed: each space's RGB basis
vectors and white are pushed through OCIO into ACES2065-1, then into CIE XYZ
using the AP0 primaries, which are definitional. Typing published primaries by
hand would risk silently wrong colour, which is the failure mode this project
exists to prevent.

Run with the interpreter that has PyOpenColorIO:
    /opt/homebrew/bin/python3.14 Tools/bake-lut/gen_spaces.py
"""
import pathlib
import sys

try:
    import numpy as np
    import PyOpenColorIO as ocio
except ImportError as e:
    sys.exit(f"needs numpy and PyOpenColorIO ({e})")

CONFIG = "studio-config-v4.0.0_aces-v2.0_ocio-v2.5"

# ACES2065-1 (AP0), from the ACES specification.
AP0 = (0.7347, 0.2653, 0.0, 1.0, 0.0001, -0.0770, 0.32168, 0.33767)

# Friendlier labels where OCIO's name is not what a Nuke or Resolve user expects.
LABELS = {
    "ACES2065-1": "ACES2065-1 (AP0)",
    "ACEScg": "ACEScg (AP1)",
    "Linear Rec.709 (sRGB)": "Rec.709 / sRGB",
    "Linear P3-D65": "P3-D65",
    "Linear Rec.2020": "Rec.2020",
    "Linear AdobeRGB": "Adobe RGB (1998)",
    "Linear ARRI Wide Gamut 3": "ARRI Wide Gamut 3",
    "Linear ARRI Wide Gamut 4": "ARRI Wide Gamut 4",
    "Linear REDWideGamutRGB": "RED Wide Gamut RGB",
    "Linear S-Gamut3": "Sony S-Gamut3",
    "Linear S-Gamut3.Cine": "Sony S-Gamut3.Cine",
    "Linear Venice S-Gamut3": "Sony Venice S-Gamut3",
    "Linear Venice S-Gamut3.Cine": "Sony Venice S-Gamut3.Cine",
    "Linear V-Gamut": "Panasonic V-Gamut",
    "Linear D-Gamut": "DJI D-Gamut",
    "Linear CinemaGamut D55": "Canon Cinema Gamut",
    "Linear BMD WideGamut Gen5": "Blackmagic Wide Gamut Gen5",
    "Linear DaVinci WideGamut": "DaVinci Wide Gamut",
}

# Order the picker the way a colourist expects: ACES first, then the common
# display gamuts, then camera vendors alphabetically.
ORDER = [
    "ACEScg", "ACES2065-1",
    "Linear Rec.709 (sRGB)", "Linear P3-D65", "Linear Rec.2020", "Linear AdobeRGB",
    "Linear ARRI Wide Gamut 3", "Linear ARRI Wide Gamut 4",
    "Linear BMD WideGamut Gen5", "Linear CinemaGamut D55",
    "Linear DaVinci WideGamut", "Linear D-Gamut",
    "Linear REDWideGamutRGB",
    "Linear S-Gamut3", "Linear S-Gamut3.Cine",
    "Linear Venice S-Gamut3", "Linear Venice S-Gamut3.Cine",
    "Linear V-Gamut",
]

def ident(name):
    out = []
    for ch in name.lower():
        out.append(ch if ch.isalnum() else "_")
    s = "".join(out)
    while "__" in s:
        s = s.replace("__", "_")
    return s.strip("_")

def rgb_to_xyz(c):
    """RGB->XYZ for a set of chromaticities, normalised to its white."""
    def xyz(x, y):
        return np.array([x / y, 1.0, (1.0 - x - y) / y])
    prim = np.column_stack([xyz(c[0], c[1]), xyz(c[2], c[3]), xyz(c[4], c[5])])
    white = xyz(c[6], c[7])
    return prim * np.linalg.solve(prim, white)

def main():
    cfg = ocio.Config.CreateFromBuiltinConfig(CONFIG)
    ap0_to_xyz = rgb_to_xyz(AP0)

    rows = []
    for name in ORDER:
        try:
            cpu = cfg.getProcessor(name, "ACES2065-1").getDefaultCPUProcessor()
        except Exception as e:
            print(f"  skipped {name}: {e}")
            continue
        basis = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 1]], dtype=np.float32)
        buf = np.ascontiguousarray(basis.copy())
        cpu.applyRGB(buf)
        xy = []
        for row in buf:                      # AP0 RGB -> XYZ -> xy
            X, Y, Z = ap0_to_xyz @ np.array(row, dtype=np.float64)
            s = X + Y + Z
            xy.extend([X / s, Y / s])
        # The Color Interop Forum ID OCIO itself assigns, so a file's
        # colorInteropID attribute maps onto this table without transcription.
        interop = cfg.getColorSpace(name).getInteropID()
        if not interop:
            sys.exit(f"{name} has no interop ID in {CONFIG}")
        # Every name OCIO knows the space by -- its name plus aliases, which
        # include older ACES config spellings ("Utility - Linear - sRGB") --
        # so a writer's colour-space attribute can be matched by name.
        names = "|".join([name] + list(cfg.getColorSpace(name).getAliases()))
        rows.append((ident(name), LABELS.get(name, name), interop, names, xy))
        print(f"  {LABELS.get(name, name):<28} "
              + " ".join(f"{v:.5f}" for v in xy[:2]) + " ...")

    root = pathlib.Path(__file__).resolve().parents[2]
    out = root / "EXRCore/src/exr_spaces_data.cpp"
    with out.open("w") as f:
        f.write("// GENERATED by Tools/bake-lut/gen_spaces.py -- do not edit.\n")
        f.write(f"// Derived from OCIO built-in config {CONFIG}\n")
        f.write("// Chromaticities are computed by pushing each space's RGB basis through\n")
        f.write("// ACES2065-1 into CIE XYZ, not transcribed from published tables.\n\n")
        f.write('#include "EXRCore/exr_spaces.h"\n\nnamespace exrcore {\n\n')
        f.write("const NamedSpace kSpaces[] = {\n")
        for id_, label, interop, names, xy in rows:
            vals = ", ".join(f"{v:.6f}f" for v in xy)
            f.write(f'    {{"{id_}", "{label}", "{interop}",\n     "{names}",\n     {{{vals}}}}},\n')
        f.write("};\n\n")
        f.write(f"const int kSpaceCount = {len(rows)};\n\n")
        f.write("}  // namespace exrcore\n")
    print(f"\n  wrote {out.relative_to(root)}  ({len(rows)} spaces)")

if __name__ == "__main__":
    main()
