#!/bin/bash
# Writes THIRD_PARTY_NOTICES.md from the licence files of exactly what is linked
# into the shipped binaries, copied verbatim from the pinned sources in Vendor/.
# The BSD licences require these notices to travel with binary redistributions,
# so Tools/build-app.sh also copies the result into the app bundle.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/Vendor/openexr/src"
# OpenEXR >= 3.4.16 vendors OpenJPH and compiles it into OpenEXRCore.
JPH="$SRC/openexr/external/OpenJPH"
OCIO_LICENSE="${OCIO_LICENSE:-$(ls /opt/homebrew/Cellar/opencolorio/*/LICENSE 2>/dev/null | tail -1)}"
OUT="$ROOT/THIRD_PARTY_NOTICES.md"

for f in "$SRC/openexr/LICENSE.md" "$SRC/Imath/LICENSE.md" "$JPH/LICENSE" \
         "$SRC/openexr/external/deflate/COPYING"; do
  [ -f "$f" ] || { echo "missing $f -- run Tools/build-openexr.sh" >&2; exit 1; }
done
[ -f "$OCIO_LICENSE" ] || { echo "OpenColorIO LICENSE not found; set OCIO_LICENSE" >&2; exit 1; }

exr_ver=$(awk -F= '/^OPENEXR_TAG=/ {sub(/^v/, "", $2); print $2}' "$ROOT/Tools/build-openexr.sh")
imath_ver=$(awk -F= '/^IMATH_TAG=/ {sub(/^v/, "", $2); print $2}' "$ROOT/Tools/build-openexr.sh")
jph_ver=$(awk '/OPENJPH_VERSION_(MAJOR|MINOR|PATCH)/ {printf "%s%s", sep, $3; sep="."}' \
          "$JPH/src/core/openjph/ojph_version.h")
deflate_ver=$(awk -F'"' '/LIBDEFLATE_VERSION_STRING/ {print $2}' \
              "$SRC/openexr/external/deflate/libdeflate.h")

section() {  # title, licence file
  printf '\n## %s\n\n```\n' "$1"
  cat "$2"
  printf '\n```\n'
}

{
  echo "# Third-party notices"
  echo
  echo "EXR Quick Look is BSD-3-Clause licensed (see LICENSE). Its binaries statically"
  echo "link the libraries below, whose licences require these notices to accompany"
  echo "any redistribution. Generated by \`Tools/make-notices.sh\` -- do not edit by hand."
  echo
  echo "## Linked into the app"
  echo
  echo "| Component | Version | Licence |"
  echo "|---|---|---|"
  echo "| OpenEXR | $exr_ver | BSD-3-Clause |"
  echo "| Imath | $imath_ver | BSD-3-Clause |"
  echo "| OpenJPH (via OpenEXR, HTJ2K) | $jph_ver | BSD-2-Clause |"
  echo "| libdeflate (bundled in OpenEXR) | $deflate_ver | MIT |"
  echo
  echo "## Used at build time only"
  echo
  echo "OpenColorIO (BSD-3-Clause) is not linked. The baked ACES 2.0 view-transform"
  echo "tables were generated with it from its built-in"
  echo "\`studio-config-v4.0.0_aces-v2.0_ocio-v2.5\` config; see docs/lut-provenance.md."
  echo "Its licence is reproduced below as attribution for that data."
  echo
  echo "ACES is a trademark of the Academy of Motion Picture Arts and Sciences. This"
  echo "project is not affiliated with or endorsed by the Academy."
  section "OpenEXR" "$SRC/openexr/LICENSE.md"
  section "Imath" "$SRC/Imath/LICENSE.md"
  section "OpenJPH" "$JPH/LICENSE"
  section "libdeflate" "$SRC/openexr/external/deflate/COPYING"
  section "OpenColorIO (build time; generated LUT data)" "$OCIO_LICENSE"
} > "$OUT"
echo "wrote ${OUT#$ROOT/}"
